
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author damarisguzman
 */
public class laucherBase extends javax.swing.JFrame {

    
  
    /**
     * Creates new form laucherBase
     */
    public laucherBase() {
        initComponents();
        
          
        SetImageLabel(imgBg,"src/pics/Fondo base.png", new Dimension (1380,800)); 
        SetImageLabel(jLabel1,"src/pics/LauncherButton0.png", new Dimension (60,60));
        SetImageLabel(jLabel2,"src/pics/LauncherButton1.png", new Dimension (60,60));
        SetImageLabel(jLabel3,"src/pics/LauncherButton2.png", new Dimension (60,60));
        SetImageLabel(jLabel4,"src/pics/LauncherButton3.png", new Dimension (60,60));
        SetImageLabel(jLabel5,"src/pics/LauncherButton4.png", new Dimension (60,60));
        SetImageLabel(jLabel6,"src/pics/LauncherButton5.png", new Dimension (60,60));
        SetImageLabel(jLabel7,"src/pics/LauncherButton6.png", new Dimension (60,60));
        SetImageLabel(jLabel8,"src/pics/LauncherButton7.png", new Dimension (60,60));
        SetImageLabel(jLabel9,"src/pics/LauncherButton8.png", new Dimension (60,60));
        SetImageLabel(jLabel10,"src/pics/LauncherButton9.png", new Dimension (60,60));
        SetImageLabel(jLabel11,"src/pics/LauncherButton10.png", new Dimension (60,60));
        SetImageLabel(jLabel12,"src/pics/LauncherButton11.png", new Dimension (60,60));
        SetImageLabel(jLabel13,"src/pics/LauncherButton12.png", new Dimension (60,60));
        SetImageLabel(jLabel14,"src/pics/LauncherButton13.png", new Dimension (60,60));
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        imgBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1380, 800));
        setMinimumSize(new java.awt.Dimension(1380, 800));
        setPreferredSize(new java.awt.Dimension(1380, 800));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMaximumSize(new java.awt.Dimension(1380, 800));
        bg.setMinimumSize(new java.awt.Dimension(1380, 800));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setMaximumSize(new java.awt.Dimension(930, 680));
        content.setOpaque(false);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 1110, 660));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 60, 60));
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 60, 60));
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 70, 60));
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 70, 60));
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 70, 60));
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 70, 60));
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 70, 60));
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, 70, 60));
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 70, 60));
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 70, 70, 60));
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 70, 70, 60));
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 70, 70, 60));
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 70, 70, 60));
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 70, 70, 60));
        bg.add(imgBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1380, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       vistaHome p1 = new vistaHome();
       ShowPanel (p1);

    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laucherBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laucherBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laucherBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laucherBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laucherBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel content;
    private javax.swing.JLabel imgBg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
  
  
private void SetImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        ImageIcon icon = new ImageIcon( image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        labelName.repaint();
    }
    private void SetImageLabel(JLabel labelName, String root, Dimension dimension){
        ImageIcon image = new ImageIcon(root);
        ImageIcon icon = new ImageIcon( image.getImage().getScaledInstance(dimension.width, dimension.height, Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        labelName.repaint();
    }

    
                                            

    private void JButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
          
       vistaHome p1 = new vistaHome();
       ShowPanel (p1);
    }                                        

    private void ShowPanel(JPanel p) {
       p.setSize(1550,880);
       p.setLocation(0, 0);
       
       content.removeAll();
       content.add(p, BorderLayout.CENTER);
       content.revalidate();
       content.repaint();
    }

}
