
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author damarisguzman
 */
public class laucherBase extends javax.swing.JFrame {

    
  
    /**
     * Creates new form laucherBase
     */
    public laucherBase() {
        initComponents();
        
          
        SetImageLabel(imgBg,"src/pics/Fondo base.png", new Dimension (1420,830)); 
        SetImageLabel(jLabel1,"src/pics/LauncherButton0.png", new Dimension (50,50));
        SetImageLabel(jLabel2,"src/pics/LauncherButton1.png", new Dimension (50,50));
        SetImageLabel(jLabel3,"src/pics/LauncherButton2.png", new Dimension (50,50));
        SetImageLabel(jLabel4,"src/pics/LauncherButton3.png", new Dimension (50,50));
        SetImageLabel(jLabel5,"src/pics/LauncherButton4.png", new Dimension (50,50));
        SetImageLabel(jLabel6,"src/pics/LauncherButton5.png", new Dimension (50,50));
        SetImageLabel(jLabel7,"src/pics/LauncherButton6.png", new Dimension (50,50));
        SetImageLabel(jLabel8,"src/pics/LauncherButton7.png", new Dimension (50,50));
        SetImageLabel(jLabel9,"src/pics/LauncherButton8.png", new Dimension (50,50));
        SetImageLabel(jLabel10,"src/pics/LauncherButton9.png", new Dimension (50,50));
        SetImageLabel(jLabel11,"src/pics/LauncherButton10.png", new Dimension (50,50));
        SetImageLabel(jLabel12,"src/pics/LauncherButton11.png", new Dimension (50,50));
        SetImageLabel(jLabel13,"src/pics/LauncherButton12.png", new Dimension (50,50));
        SetImageLabel(jLabel14,"src/pics/LauncherButton13.png", new Dimension (50,50));
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        imgBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1420, 830));
        setMinimumSize(new java.awt.Dimension(1420, 830));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1420, 830));
        setSize(new java.awt.Dimension(1420, 830));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMaximumSize(new java.awt.Dimension(1420, 830));
        bg.setMinimumSize(new java.awt.Dimension(1420, 830));
        bg.setPreferredSize(new java.awt.Dimension(1420, 830));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setMaximumSize(new java.awt.Dimension(930, 680));
        content.setOpaque(false);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 1130, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel1.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel1.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel1.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel1.add(jLabel4);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel1.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel1.add(jLabel6);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel1.add(jLabel7);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel1.add(jLabel8);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel1.add(jLabel9);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jPanel1.add(jLabel10);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jPanel1.add(jLabel11);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPanel1.add(jLabel12);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jPanel1.add(jLabel13);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        jPanel1.add(jLabel14);

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 1090, 60));

        imgBg.setMaximumSize(new java.awt.Dimension(1430, 830));
        imgBg.setMinimumSize(new java.awt.Dimension(1430, 830));
        bg.add(imgBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
         SetImageLabel(jLabel1,"src/pics/LauncherButton0.png", new Dimension (60,60));

    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
          SetImageLabel(jLabel1,"src/pics/LauncherButton0.png", new Dimension (50,50));

    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
       SetImageLabel(jLabel2,"src/pics/LauncherButton1.png", new Dimension (60,60));

    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
         SetImageLabel(jLabel2,"src/pics/LauncherButton1.png", new Dimension (50,50));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
         SetImageLabel(jLabel3,"src/pics/LauncherButton2.png", new Dimension (60,60));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        SetImageLabel(jLabel3,"src/pics/LauncherButton2.png", new Dimension (50,50));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
         SetImageLabel(jLabel4,"src/pics/LauncherButton3.png", new Dimension (60,60));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
         SetImageLabel(jLabel4,"src/pics/LauncherButton3.png", new Dimension (50,50));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
       SetImageLabel(jLabel5,"src/pics/LauncherButton4.png", new Dimension (60,60));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
         SetImageLabel(jLabel5,"src/pics/LauncherButton4.png", new Dimension (50,50));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        SetImageLabel(jLabel6,"src/pics/LauncherButton5.png", new Dimension (60,60));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
         SetImageLabel(jLabel6,"src/pics/LauncherButton5.png", new Dimension (50,50));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        SetImageLabel(jLabel7,"src/pics/LauncherButton6.png", new Dimension (60,60));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
         SetImageLabel(jLabel7,"src/pics/LauncherButton6.png", new Dimension (50,50));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
         SetImageLabel(jLabel8,"src/pics/LauncherButton7.png", new Dimension (60,60));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
         SetImageLabel(jLabel8,"src/pics/LauncherButton7.png", new Dimension (50,50));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        SetImageLabel(jLabel9,"src/pics/LauncherButton8.png", new Dimension (60,60));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
       SetImageLabel(jLabel9,"src/pics/LauncherButton8.png", new Dimension (50,50));
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
       SetImageLabel(jLabel10,"src/pics/LauncherButton9.png", new Dimension (60,60));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
         SetImageLabel(jLabel10,"src/pics/LauncherButton9.png", new Dimension (50,50));
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
         SetImageLabel(jLabel11,"src/pics/LauncherButton10.png", new Dimension (60,60));
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        SetImageLabel(jLabel11,"src/pics/LauncherButton10.png", new Dimension (50,50));
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
         SetImageLabel(jLabel12,"src/pics/LauncherButton11.png", new Dimension (60,60));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        SetImageLabel(jLabel12,"src/pics/LauncherButton11.png", new Dimension (50,50));
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        SetImageLabel(jLabel13,"src/pics/LauncherButton12.png", new Dimension (60,60));
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
         SetImageLabel(jLabel13,"src/pics/LauncherButton12.png", new Dimension (50,50));
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
         SetImageLabel(jLabel14,"src/pics/LauncherButton13.png", new Dimension (60,60));
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
       SetImageLabel(jLabel14,"src/pics/LauncherButton1.png", new Dimension (50,50));
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      CrearHome(); 
      String jsonString;
        try {
            jsonString = getJson();
            int index = 0;// Índice del grado y del juego
            laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
            List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
            for (Juego juego : juegos) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       CrearHome(); 
       String jsonString;
        try {
            jsonString = getJson();
            int index = 1;// Índice del grado y del juego
            laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
            List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
           for (Juego juego : juegos) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       CrearHome(); 
       String jsonString;
        try {
            jsonString = getJson();
            int index = 2;// Índice del grado y del juego
            laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
            List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
           for (Juego juego : juegos) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       CrearHome();  
       String jsonString;
        try {
            jsonString = getJson();
            int index = 3;// Índice del grado y del juego
            laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
            List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
           for (Juego juego : juegos) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       CrearHome();  
       String jsonString;
        try {
            jsonString = getJson();
            int index = 4;// Índice del grado y del juego
            laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
            List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
           for (Juego juego : juegos) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       CrearHome();  
       String jsonString;
        try {
            jsonString = getJson();
            int index = 5;// Índice del grado y del juego
            laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
            List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
           for (Juego juego : juegos) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       CrearHome();  
       String jsonString;
        try {
            jsonString = getJson();
            int index = 6;// Índice del grado y del juego
            laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
            List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
           for (Juego juego : juegos) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       CrearHome();  
       String jsonString;
        try {
            jsonString = getJson();
            int index = 7;// Índice del grado y del juego
            laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
            List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
           for (Juego juego : juegos) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       CrearHome();   
       String jsonString;
        try {
            jsonString = getJson();
            int index = 8;// Índice del grado y del juego
            laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
            List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
           for (Juego juego : juegos) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       CrearHome(); 
       String jsonString;
        try {
            jsonString = getJson();
            int index = 9;// Índice del grado y del juego
            laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
            List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
           for (Juego juego : juegos) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       CrearHome(); 
       String jsonString;
        try {
            jsonString = getJson();
            int index = 10;// Índice del grado y del juego
            laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
            List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
           for (Juego juego : juegos) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
       CrearHome();
       String jsonString;
        try {
            jsonString = getJson();
            int index = 11;// Índice del grado y del juego
            laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
            List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
           for (Juego juego : juegos) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
       CrearHome();
       String jsonString;
        try {
           jsonString = getJson();
           int index = 12;// Índice del grado y del juego
           laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
           Grado grado = getGradosInfo(jsonString, index);
           System.out.println("Nombre del grado: " + grado.getNombre());
           List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
           for (Juego juego : juegos) {
           System.out.println("Título del Juego: " + juego.getTitulo());
           System.out.println("Imagen del Juego: " + juego.getImagen());
           }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
       CrearHome();
       String jsonString;
        try {
            jsonString = getJson();
            int index = 13;// Índice del grado y del juego
            laucherBase.setClickedGradoIndex(index);// Establecer el índice del grado clickeado
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
            List<Juego> juegos = getJuegoEspecifico(jsonString, index, 0, 5);
           for (Juego juego : juegos) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            }   
            
        } catch (JSONException | IOException ex) {
            Logger.getLogger(laucherBase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     * @throws org.json.JSONException
     */
    public static void main(String args[]) throws IOException, JSONException {
      
           String jsonString = new String(Files.readAllBytes(Paths.get("src/BaseDeDatos.json")));
                    
        // Imprimir los datos para verificar
        for (int index = 0; index < 14; index++) {
            Grado grado = getGradosInfo(jsonString, index);
            System.out.println("Nombre del grado: " + grado.getNombre());
             for (Juego juego : grado.getJuegos()) {
            System.out.println("Título del Juego: " + juego.getTitulo());
            System.out.println("Imagen del Juego: " + juego.getImagen());
            System.out.println("Ruta del Juego: " + juego.getRuta());
            System.out.println("Descripción del Juego: " + juego.getDescripcion());
             }
}
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laucherBase().setVisible(true);
            }
        });
    }
    public static String getJson() throws IOException {
        String jsonString = new String(Files.readAllBytes(Paths.get("src/BaseDeDatos.json")));
        return jsonString;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel content;
    private javax.swing.JLabel imgBg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
  
  

    private void SetImageLabel(JLabel labelName, String root, Dimension dimension){
        ImageIcon image = new ImageIcon(root);
        ImageIcon icon = new ImageIcon( image.getImage().getScaledInstance(dimension.width, dimension.height, Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        labelName.repaint();
    }

    public void CrearHome() {
        vistaHome p1 = new vistaHome();
        p1.parent = this;
        ShowPanel (p1);
    }
                                                                                 

    public void ShowPanel(JPanel p) {
       p.setSize(1110,660);
       p.setLocation(0, 0);
       
       content.removeAll();
       content.add(p, BorderLayout.CENTER);
       content.revalidate();
       content.repaint();
    }
    
    public static Grado getGradosInfo(String jsonString, int gradoIndex) throws JSONException {
       JSONObject jsonObject = new JSONObject(jsonString);
       JSONArray gradosArray = jsonObject.getJSONArray("grados");

        if (gradoIndex < 0 || gradoIndex >= gradosArray.length()) {
            throw new IllegalArgumentException("Índice de grado fuera de rango.");
        }

        JSONObject gradoObject = gradosArray.getJSONObject(gradoIndex);
        String nombre = gradoObject.getString("nombre");

        JSONArray juegosArray = gradoObject.getJSONArray("juegos");
        List<Juego> juegosList = new ArrayList<>();

        for (int j = 0; j < juegosArray.length(); j++) {
            JSONObject juegoObject = juegosArray.getJSONObject(j);
            String titulo = juegoObject.getString("titulo");
            String imagen = juegoObject.getString("imagen");
            String ruta = juegoObject.getString("ruta");
            String descripcion = juegoObject.getString("descripcion");

            Juego juego = new Juego(titulo, imagen, ruta, descripcion);
            juegosList.add(juego);
        }

        return new Grado(nombre, juegosList); 
    }
      public static List<Juego> getJuegoEspecifico(String jsonString, int gradoIndex, int startIndex, int endIndex ) throws JSONException {
        Grado grado = getGradosInfo(jsonString, gradoIndex);

        if (startIndex < 0 || endIndex >= grado.getJuegos().size() || startIndex > endIndex) {
            throw new IllegalArgumentException("Índice de juego fuera de rango.");
        }

         return grado.getJuegos().subList(startIndex, endIndex + 1);    
      }
     private static int clickedGradoIndex = -1; // Variable para almacenar el índice del grado clickeado

     public static void setClickedGradoIndex(int index) {
        clickedGradoIndex = index;
    }

     public static int getClickedGradoIndex() {
        return clickedGradoIndex;
    }
}
