import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author damarisguzman
 */
public class vistaHome extends javax.swing.JPanel {

    public laucherBase parent;
    public vistaHome() {
        initComponents();
        SetImageLabel(grado0,"src/pics/Grado0.png", new Dimension (255,190)); 
        SetImageLabel(grado1,"src/pics/Grado1.png", new Dimension (255,190)); 
        SetImageLabel(grado2,"src/pics/Grado2.png", new Dimension (255,190)); 
        SetImageLabel(grado3,"src/pics/Grado3.png", new Dimension (255,190)); 
        SetImageLabel(grado4,"src/pics/Grado4.png", new Dimension (255,190)); 
        SetImageLabel(grado5,"src/pics/Grado5.png", new Dimension (255,190)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        grado0 = new javax.swing.JLabel();
        grado1 = new javax.swing.JLabel();
        grado2 = new javax.swing.JLabel();
        grado3 = new javax.swing.JLabel();
        grado4 = new javax.swing.JLabel();
        grado5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(14, 77, 144));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1110, 660));
        setMinimumSize(new java.awt.Dimension(1110, 660));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1110, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        grado0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grado0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Grado0.png"))); // NOI18N
        grado0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grado0.setMaximumSize(new java.awt.Dimension(370, 291));
        grado0.setMinimumSize(new java.awt.Dimension(370, 291));
        grado0.setPreferredSize(new java.awt.Dimension(370, 280));
        grado0.setRequestFocusEnabled(false);
        grado0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grado0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grado0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grado0MouseExited(evt);
            }
        });
        jPanel1.add(grado0);

        grado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Grado1.png"))); // NOI18N
        grado1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grado1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grado1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grado1MouseExited(evt);
            }
        });
        jPanel1.add(grado1);

        grado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Grado2.png"))); // NOI18N
        grado2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grado2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grado2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grado2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grado2MouseExited(evt);
            }
        });
        jPanel1.add(grado2);

        grado3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Grado3.png"))); // NOI18N
        grado3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grado3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grado3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grado3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grado3MouseExited(evt);
            }
        });
        jPanel1.add(grado3);

        grado4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grado4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Grado4.png"))); // NOI18N
        grado4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grado4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grado4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grado4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grado4MouseExited(evt);
            }
        });
        jPanel1.add(grado4);

        grado5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grado5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Grado5.png"))); // NOI18N
        grado5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grado5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grado5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grado5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grado5MouseExited(evt);
            }
        });
        jPanel1.add(grado5);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void grado0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado0MouseEntered
        SetImageLabel(grado0,"src/pics/Grado0.png", new Dimension (270,200)); 
    }//GEN-LAST:event_grado0MouseEntered

    private void grado0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado0MouseExited
         SetImageLabel(grado0,"src/pics/Grado0.png", new Dimension (255,190)); 
    }//GEN-LAST:event_grado0MouseExited

    private void grado1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado1MouseEntered
        SetImageLabel(grado1,"src/pics/Grado1.png", new Dimension (270,200)); 
    }//GEN-LAST:event_grado1MouseEntered

    private void grado1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado1MouseExited
      SetImageLabel(grado1,"src/pics/Grado1.png", new Dimension (255,190)); 
    }//GEN-LAST:event_grado1MouseExited

    private void grado2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado2MouseEntered
        SetImageLabel(grado2,"src/pics/Grado2.png", new Dimension (270,200)); 
    }//GEN-LAST:event_grado2MouseEntered

    private void grado2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado2MouseExited
        SetImageLabel(grado2,"src/pics/Grado2.png", new Dimension (255,190)); 
    }//GEN-LAST:event_grado2MouseExited

    private void grado3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado3MouseEntered
        SetImageLabel(grado3,"src/pics/Grado3.png", new Dimension (270,200)); 
    }//GEN-LAST:event_grado3MouseEntered

    private void grado3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado3MouseExited
         SetImageLabel(grado3,"src/pics/Grado3.png", new Dimension (255,190)); 
    }//GEN-LAST:event_grado3MouseExited

    private void grado4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado4MouseEntered
        SetImageLabel(grado4,"src/pics/Grado4.png", new Dimension (270,200)); 
    }//GEN-LAST:event_grado4MouseEntered

    private void grado4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado4MouseExited
        SetImageLabel(grado4,"src/pics/Grado4.png", new Dimension (255,190)); 
    }//GEN-LAST:event_grado4MouseExited

    private void grado5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado5MouseEntered
         SetImageLabel(grado5,"src/pics/Grado5.png", new Dimension (270,200)); 
    }//GEN-LAST:event_grado5MouseEntered

    private void grado5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado5MouseExited
        SetImageLabel(grado5,"src/pics/Grado5.png", new Dimension (255,190)); 
    }//GEN-LAST:event_grado5MouseExited

    private void grado0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado0MouseClicked
        vistaGame jPanel1 = new vistaGame();
        parent.ShowPanel(jPanel1);
    }//GEN-LAST:event_grado0MouseClicked

    private void grado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado1MouseClicked
        vistaGame jPanel1 = new vistaGame();
        parent.ShowPanel(jPanel1);
    }//GEN-LAST:event_grado1MouseClicked

    private void grado2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado2MouseClicked
        vistaGame jPanel1 = new vistaGame();
        parent.ShowPanel(jPanel1);
    }//GEN-LAST:event_grado2MouseClicked

    private void grado3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado3MouseClicked
        vistaGame jPanel1 = new vistaGame();
        parent.ShowPanel(jPanel1);
    }//GEN-LAST:event_grado3MouseClicked

    private void grado4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado4MouseClicked
        vistaGame jPanel1 = new vistaGame();
        parent.ShowPanel(jPanel1);
    }//GEN-LAST:event_grado4MouseClicked

    private void grado5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado5MouseClicked
        vistaGame jPanel1 = new vistaGame();
        parent.ShowPanel(jPanel1);
    }//GEN-LAST:event_grado5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel grado0;
    private javax.swing.JLabel grado1;
    private javax.swing.JLabel grado2;
    private javax.swing.JLabel grado3;
    private javax.swing.JLabel grado4;
    private javax.swing.JLabel grado5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


    private void SetImageLabel(JLabel labelName, String root, Dimension dimension){
        ImageIcon image = new ImageIcon(root);
        ImageIcon icon = new ImageIcon( image.getImage().getScaledInstance(dimension.width, dimension.height, Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        labelName.repaint();
    }
}
