
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author damarisguzman
 */
public class vistaHome extends javax.swing.JPanel {

    /**
     * Creates new form vistaHome
     */
    public vistaHome() {
        initComponents();
        SetImageLabel(grado0,"src/pics/Grado0.png", new Dimension (255,150)); 
        SetImageLabel(grado1,"src/pics/Grado1.png", new Dimension (255,150)); 
        SetImageLabel(grado2,"src/pics/Grado2.png", new Dimension (255,150)); 
        SetImageLabel(grado3,"src/pics/Grado3.png", new Dimension (255,150)); 
        SetImageLabel(grado4,"src/pics/Grado4.png", new Dimension (255,150)); 
        SetImageLabel(grado5,"src/pics/Grado5.png", new Dimension (255,150)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grado0 = new javax.swing.JLabel();
        grado1 = new javax.swing.JLabel();
        grado2 = new javax.swing.JLabel();
        grado3 = new javax.swing.JLabel();
        grado4 = new javax.swing.JLabel();
        grado5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(14, 77, 144));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(930, 680));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(930, 680));

        grado0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grado0MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grado0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grado3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grado1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grado4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(grado2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grado5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grado1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grado0, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grado2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grado3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grado4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grado5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void grado0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grado0MouseClicked
        vistaGame p2 = new vistaGame();
       ShowPanel (p2);

    }//GEN-LAST:event_grado0MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel grado0;
    private javax.swing.JLabel grado1;
    private javax.swing.JLabel grado2;
    private javax.swing.JLabel grado3;
    private javax.swing.JLabel grado4;
    private javax.swing.JLabel grado5;
    // End of variables declaration//GEN-END:variables

private void SetImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        ImageIcon icon = new ImageIcon( image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        labelName.repaint();
    }
    private void SetImageLabel(JLabel labelName, String root, Dimension dimension){
        ImageIcon image = new ImageIcon(root);
        ImageIcon icon = new ImageIcon( image.getImage().getScaledInstance(dimension.width, dimension.height, Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        labelName.repaint();
    }
 private void ShowPanel(JPanel p) {
       p.setSize(1550,880);
       p.setLocation(0, 0);
       
       jPanel1.removeAll();
       jPanel1.add(p, BorderLayout.CENTER);
       jPanel1.revalidate();
       jPanel1.repaint();
    }

    
}
